export interface GameSummary {
  id: string;
  status: string;
  coverage: string;
  scheduled: string;
  duration: string;
  attendance: number;
  lead_changes: number;
  times_tied: number;
  clock: string;
  quarter: number;
  track_on_court: boolean;
  reference: string;
  entry_mode: string;
  sr_id: string;
  time_zones: TimeZones;
  venue: Venue;
  home: Home;
  away: Away;
  officials?: OfficialsEntity[] | null;
}
export interface TimeZones {
  venue: string;
  home: string;
  away: string;
}
export interface Venue {
  id: string;
  name: string;
  capacity: number;
  address: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  sr_id: string;
}
export interface Home {
  name: string;
  alias: string;
  market: string;
  id: string;
  points: number;
  bonus: boolean;
  sr_id: string;
  reference: string;
  scoring?: ScoringEntity[] | null;
  statistics: Statistics;
  coaches?: CoachesEntity[] | null;
  players?: PlayersEntitySummary[] | null;
}
export interface ScoringEntity {
  type: string;
  number: number;
  sequence: number;
  points: number;
}
export interface Statistics {
  minutes: string;
  field_goals_made: number;
  field_goals_att: number;
  field_goals_pct: number;
  three_points_made: number;
  three_points_att: number;
  three_points_pct: number;
  two_points_made: number;
  two_points_att: number;
  two_points_pct: number;
  blocked_att: number;
  free_throws_made: number;
  free_throws_att: number;
  free_throws_pct: number;
  offensive_rebounds: number;
  defensive_rebounds: number;
  assists: number;
  steals: number;
  blocks: number;
  assists_turnover_ratio: number;
  personal_fouls: number;
  ejections: number;
  foulouts: number;
  points: number;
  fast_break_pts: number;
  second_chance_pts: number;
  team_turnovers: number;
  points_off_turnovers: number;
  team_rebounds: number;
  flagrant_fouls: number;
  player_tech_fouls: number;
  team_tech_fouls: number;
  coach_tech_fouls: number;
  points_in_paint: number;
  rebounds: number;
  turnovers: number;
  pls_min: number;
  effective_fg_pct: number;
  bench_points: number;
  points_in_paint_att: number;
  points_in_paint_made: number;
  points_in_paint_pct: number;
  true_shooting_att: number;
  true_shooting_pct: number;
  biggest_lead: number;
  fouls_drawn: number;
  offensive_fouls: number;
  efficiency: number;
  efficiency_game_score: number;
  defensive_rating: number;
  offensive_rating: number;
  coach_ejections: number;
  points_against: number;
  possessions: number;
  opponent_possessions: number;
  team_defensive_rebounds: number;
  team_offensive_rebounds: number;
  time_leading: string;
  defensive_points_per_possession: number;
  offensive_points_per_possession: number;
  team_fouls: number;
  total_rebounds: number;
  total_fouls: number;
  second_chance_att: number;
  second_chance_made: number;
  second_chance_pct: number;
  fast_break_att: number;
  fast_break_made: number;
  fast_break_pct: number;
  most_unanswered: MostUnanswered;
  periods?: PeriodsEntity[] | null;
}
export interface MostUnanswered {
  points: number;
  own_score: number;
  opp_score: number;
}
export interface PeriodsEntity {
  type: string;
  id: string;
  number: number;
  sequence: number;
  minutes: string;
  field_goals_made: number;
  field_goals_att: number;
  field_goals_pct: number;
  three_points_made: number;
  three_points_att: number;
  three_points_pct: number;
  two_points_made: number;
  two_points_att: number;
  two_points_pct: number;
  blocked_att: number;
  free_throws_made: number;
  free_throws_att: number;
  free_throws_pct: number;
  offensive_rebounds: number;
  defensive_rebounds: number;
  rebounds: number;
  assists: number;
  turnovers: number;
  steals: number;
  blocks: number;
  assists_turnover_ratio: number;
  personal_fouls: number;
  offensive_fouls: number;
  points: number;
  fast_break_pts: number;
  second_chance_pts: number;
  team_turnovers: number;
  points_off_turnovers: number;
  team_rebounds: number;
  flagrant_fouls: number;
  player_tech_fouls: number;
  team_tech_fouls: number;
  coach_tech_fouls: number;
  pls_min: number;
  effective_fg_pct: number;
  bench_points: number;
  points_in_paint: number;
  points_in_paint_att: number;
  points_in_paint_made: number;
  points_in_paint_pct: number;
  true_shooting_att: number;
  true_shooting_pct: number;
  biggest_lead: number;
  fouls_drawn: number;
  efficiency: number;
  efficiency_game_score: number;
  defensive_rating: number;
  offensive_rating: number;
  points_against: number;
  possessions: number;
  opponent_possessions: number;
  team_defensive_rebounds: number;
  team_offensive_rebounds: number;
  time_leading: string;
  defensive_points_per_possession: number;
  offensive_points_per_possession: number;
  team_fouls: number;
  total_rebounds: number;
  total_fouls: number;
  second_chance_att: number;
  second_chance_made: number;
  second_chance_pct: number;
  fast_break_att: number;
  fast_break_made: number;
  fast_break_pct: number;
}
export interface CoachesEntity {
  full_name: string;
  first_name: string;
  last_name: string;
  position: string;
  reference: string;
  id?: string | null;
}
export interface PlayersEntitySummary {
  full_name: string;
  jersey_number: string;
  id: string;
  first_name: string;
  last_name: string;
  position: string;
  primary_position: string;
  active?: boolean | null;
  not_playing_reason?: string | null;
  not_playing_description?: string | null;
  on_court: boolean;
  sr_id: string;
  reference: string;
  statistics: Statistics1;
  played?: boolean | null;
  starter?: boolean | null;
}
export interface Statistics1 {
  minutes: string;
  field_goals_made: number;
  field_goals_att: number;
  field_goals_pct: number;
  three_points_made: number;
  three_points_att: number;
  three_points_pct: number;
  two_points_made: number;
  two_points_att: number;
  two_points_pct: number;
  blocked_att: number;
  free_throws_made: number;
  free_throws_att: number;
  free_throws_pct: number;
  offensive_rebounds: number;
  defensive_rebounds: number;
  rebounds: number;
  assists: number;
  turnovers: number;
  steals: number;
  blocks: number;
  assists_turnover_ratio: number;
  personal_fouls: number;
  tech_fouls: number;
  flagrant_fouls: number;
  pls_min: number;
  points: number;
  double_double: boolean;
  triple_double: boolean;
  effective_fg_pct: number;
  efficiency: number;
  efficiency_game_score: number;
  points_in_paint: number;
  points_in_paint_att: number;
  points_in_paint_made: number;
  points_in_paint_pct: number;
  true_shooting_att: number;
  true_shooting_pct: number;
  fouls_drawn: number;
  offensive_fouls: number;
  points_off_turnovers: number;
  second_chance_pts: number;
  fast_break_pts: number;
  fast_break_att: number;
  fast_break_made: number;
  fast_break_pct: number;
  coach_ejections: number;
  minus: number;
  plus: number;
  defensive_rebounds_pct: number;
  offensive_rebounds_pct: number;
  rebounds_pct: number;
  steals_pct: number;
  turnovers_pct: number;
  coach_tech_fouls: number;
  second_chance_att: number;
  second_chance_made: number;
  second_chance_pct: number;
  periods?: PeriodsEntity1[] | null;
  defensive_rating?: number | null;
  offensive_rating?: number | null;
}
export interface PeriodsEntity1 {
  type: string;
  id: string;
  number: number;
  sequence: number;
  minutes: string;
  field_goals_made: number;
  field_goals_att: number;
  field_goals_pct: number;
  three_points_made: number;
  three_points_att: number;
  three_points_pct: number;
  two_points_made: number;
  two_points_att: number;
  two_points_pct: number;
  blocked_att: number;
  free_throws_made: number;
  free_throws_att: number;
  free_throws_pct: number;
  offensive_rebounds: number;
  defensive_rebounds: number;
  rebounds: number;
  assists: number;
  turnovers: number;
  steals: number;
  blocks: number;
  assists_turnover_ratio: number;
  personal_fouls: number;
  offensive_fouls: number;
  tech_fouls: number;
  flagrant_fouls: number;
  pls_min: number;
  points: number;
  effective_fg_pct: number;
  efficiency: number;
  efficiency_game_score: number;
  points_in_paint: number;
  points_in_paint_att: number;
  points_in_paint_made: number;
  points_in_paint_pct: number;
  true_shooting_att: number;
  true_shooting_pct: number;
  fouls_drawn: number;
  points_off_turnovers: number;
  second_chance_pts: number;
  fast_break_pts: number;
  fast_break_att: number;
  fast_break_made: number;
  fast_break_pct: number;
  minus: number;
  plus: number;
  defensive_rebounds_pct: number;
  offensive_rebounds_pct: number;
  rebounds_pct: number;
  steals_pct: number;
  turnovers_pct: number;
  second_chance_att: number;
  second_chance_made: number;
  second_chance_pct: number;
  defensive_rating?: number | null;
  offensive_rating?: number | null;
}
export interface Away {
  name: string;
  alias: string;
  market: string;
  id: string;
  points: number;
  bonus: boolean;
  sr_id: string;
  reference: string;
  scoring?: ScoringEntity[] | null;
  statistics: Statistics;
  coaches?: CoachesEntity1[] | null;
  players?: PlayersEntitySummary[] | null;
}
export interface CoachesEntity1 {
  full_name: string;
  first_name: string;
  last_name: string;
  position: string;
  reference: string;
}
export interface OfficialsEntity {
  id: string;
  full_name: string;
  first_name: string;
  last_name: string;
  number: string;
  assignment: string;
  experience: string;
}
